# Command to run to execute a Debian update
cron_upgrade_job: /bin/yum -y upgrade ; /bin/yum -y autoremove

# Tools to install on Debian hosts
tools_package:
  - sudo
  - curl
  - sed
  - grep
  - net-tools
