---
- name: Update mail aliases.
  lineinfile:
    dest: "{{ aliases_config_file }}"
    line: "{{ backup_user_git }}: {{ backup_git_mail_target }}"
    regexp: "^{{ backup_user_git }}:"
  notify: update aliases
