---
# defaults file for backup_client

# Name of the Cron service and cron package (depends on your OS, can be cron, cronie, crond...)
cron_client_service_name: cron
cron_client_package: cron

# Name of the Borkbackup package
borgbackup_package: borgbackup

# Backup client folders to backup (separated with a space)
backup_client_folders_to_backup: ""

# Folder to deploy backup client scripts
backup_client_scripts_folder: "/usr/local/sbin"

# Backup client user and home directory
backup_client_user: "root"
backup_client_user_home: "/root"

# Crontask backup client scheduling
backup_client_cron_weekday: "*"
backup_client_cron_hour: "1"
backup_client_cron_minute: "30"

# Alias config file
aliases_config_file: "/etc/aliases"

# User or email to send client backup scripts report
backup_client_mail_target: "root"

# Compression parameters
backup_client_compression_param: "lzma,9"
