---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: package.yml
- include_tasks: service.yml
- include_tasks: cert.yml
- include_tasks: ldap_tls.yml
- include_tasks: ldap_entries.yml
- include_tasks: ldap_attributes.yml
- include_tasks: ldap_config.yml
