---
- hosts: all
  roles:
    - auto_reboot
    - auto_upgrade
    - sysctl_customizations
    - client_ntp
    - client_resolvers
    - client_tools
    - role: users_sudo
      when: "'mail_server' not in group_names"
    - client_iptables
    - postfix
