---
- hosts: all
  roles:
    - auto_reboot
    - auto_upgrade
#    - client_ntp
#    - client_resolvers
#    - client_tools
#    - users_sudo
    - client_iptables
#    - munin-node
#    - munin-async

