---
- hosts: all
  roles:
#    - auto_reboot
#    - auto_upgrade
#    - client_ntp
#    - client_resolvers
#    - client_tools
#    - users_sudo
    - client_iptables # OK for Debian (iptables-persistent mode)
