---
- hosts: all
  roles:
    - auto_reboot
    - auto_upgrade
    - client_iptables # OK for Debian (iptables-persistent mode)
    - client_ntp
    - client_resolvers
    - client_tools
    - users_sudo
