---
- name: Create SSH directory for Munin user
  file:
    path: "{{ munin_home_directory + '/.ssh' }}"
    state: directory
    owner: "{{ munin_user }}"
    group: "{{ munin_user }}"
    mode: '0700'
- name: Deploy private key to access other Munin node
  copy:
    dest: "{{ munin_home_directory + '/.ssh/id_rsa' }}"
    owner: "{{ munin_user }}"
    group: "{{ munin_user }}"
    mode: '0600'
    content: "{{ private_key_munin_user_host }}"
- name: Deploy public key to access other Munin node
  copy:
    dest: "{{ munin_home_directory + '/.ssh/id_rsa.pub' }}"
    owner: "{{ munin_user }}"
    group: "{{ munin_user }}"
    mode: '0644'
    content: "{{ public_key_munin_user_host + '\n' }}"
