---
- name: save iptables v4 rules
  shell: iptables-save > {{ iptables_save_file }}
  listen: persist iptables

- name: save iptables v6 rules
  shell: ip6tables-save > {{ ip6tables_save_file }}
  listen: persist iptables
