---
# Main tasks file for users_sudo

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- import_tasks: package.yml
- import_tasks: group.yml
- import_tasks: users.yml

