---

icinga2_server_apt_repository: "deb http://packages.icinga.com/{{ ansible_distribution|lower }} icinga-{{ ansible_distribution_release }} main"
icinga2_server_apt_key: "http://packages.icinga.com/icinga.key"

icinga2_server_icinga2_package: icinga2
icinga2_server_monitoring_plugins_package: monitoring-plugins

icinga2_server_icinga2_service: icinga2

icinga2_server_mariadb_server_package: mariadb-server
icinga2_server_mariadb_client_package: mariadb-client
icinga2_server_mariadb_python_package: python-mysqldb
icinga2_server_icinga2_ido_mysql_package: icinga2-ido-mysql
icinga2_server_icingaweb2_package: icingaweb2
icinga2_server_icingacli_package: icingacli
icinga2_server_apache_httpd_package: apache2
icinga2_server_apache_httpd_service: apache2

icinga2_server_user: nagios
icinga2_server_group: nagios

icinga2_server_mariadb_service: mariadb

icinga2_server_mariadb_root_password: needToBeChanged

icinga2_server_mariadb_bind_address: '127.0.0.1'
icinga2_server_mariadb_performance_schema: on
icinga2_server_mariadb_skip_name_resolve: 1
icinga2_server_mariadb_max_connections: 100
icinga2_server_mariadb_connect_timeout: 2
icinga2_server_mariadb_max_allowed_packet: 10M
icinga2_server_mariadb_innodb_buffer_pool_instances: 1
icinga2_server_mariadb_innodb_buffer_pool_size: 100M
icinga2_server_mariadb_innodb_log_file_size: 25M
icinga2_server_mariadb_table_cache: 1000
icinga2_server_mariadb_tmp_table_size: 50M
icinga2_server_mariadb_max_heap_table_size: 50M
icinga2_server_mariadb_query_cache_limit: 256K
icinga2_server_mariadb_query_cache_type: 0
icinga2_server_mariadb_query_cache_size: 0
icinga2_server_mariadb_query_cache_min_res_unit: 2k
icinga2_server_mariadb_join_buffer_size: 2M
icinga2_server_mariadb_sort_buffer_size: 256K
icinga2_server_mariadb_read_buffer_size: 128K
icinga2_server_mariadb_read_rnd_buffer_size: 4M
icinga2_server_mariadb_key_buffer: 500M
icinga2_server_mariadb_slow_query_log: true
icinga2_server_mariadb_long_query_time: 5
icinga2_server_mariadb_log_slow_admin_statements: true
icinga2_server_mariadb_log_queries_not_using_indexes: true

icinga2_server_mariadb_databases:
  - icinga
  - icingaweb2

icinga2_server_mariadb_users:
  icinga_user:
    name: "icinga_user"
    password: "needToBeChanged"
    priv: "icinga.*:ALL"
  icingaweb2_user:
    name: "icingaweb2_user"
    password: "needToBeChanged"
    priv: "icinga.*:ALL"

icinga2_server_mariadb_icinga_schema_location: "/usr/share/icinga2-ido-mysql/schema/mysql.sql"

icinga2_server_api_users:
  - username: root
    password: 'needToBeChanged'
    permissions: '*'

