---
# Install tools task
- name: Tools installed
  package:
    name: "{{ tools_package }}"
    state: present
#  loop: "{{ tools_package }}"
  when: tools_package is defined and (tools_package|length>0)

