---
munin_node_log: /var/log/munin/munin-node.log
munin_node_pid: /var/run/munin-node.pid
munin_plugin_src_path: /usr/local/libexec/munin/plugins
munin_node_service: munin_node
munin_node_group: wheel
