---
# defaults file for client_resolvers

# DNS resolvers to use
resolvers:
  - 2001:910:800::40
  - 80.67.169.12
  - 2001:913::8
  - 80.67.188.188

# Domain to use in the DNS "search" resolver field
main_domain: wirebrass.fr
