---
# defaults file for client_reboot

# Cron task scheduling for auto reboot
cron_reboot_minute: "0"
cron_reboot_hour: "3"
cron_reboot_day: "*"
cron_reboot_month: "*"
cron_reboot_weekday: "*"

# Set to true if you want to enable auto reboot
auto_reboot: false

# Name of the cron service and cron package (depends on your OS, can be cron, cronie, crond...)
cron_service_name: cron
cron_package: cron
