---
# handlers file for backup_client

- name: "restart cron"
  service:
    name: "{{ cron_service_name }}"
    enabled: yes
    state: restarted

- name: update aliases
  command: postalias {{ aliases_config_file }}
