galaxy_info:
  author: nemo
  description: Install tools on a GNU/Linux host.
  company: Wirebrass

  license: license (BSD)

  min_ansible_version: 2.4

  platforms:
    - name: Debian
      versions:
        - stretch
        - buster
    - name: Gentoo
      versions:
        - all

  galaxy_tags:
    - tools
    - system
    - server
    - install
    - package

dependencies: []
