---
# Main tasks file for auto_upgrade

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  when: auto_upgrade

- import_tasks: package.yml
- import_tasks: crontask.yml
